### ISSUE TITLE
can not run? ModuleNotFoundError: No module named 'lib.sqldb'

### ISSUE THREAD

**Issue by scsdev-cyber** [675354981/JR-scan#3]
:~/JR-scan# python3 ./JR.py
Traceback (most recent call last):
  File "./JR.py", line 5, in <module>
    from report import gener
  File "/root/JR-scan/report.py", line 4, in <module>
    from lib.sqldb import Sqldb
ModuleNotFoundError: No module named 'lib.sqldb'

**Comment by scsdev-cyber** [comment]
create __init__.py file in the folders then resolve the issue
